#!/bin/bash
while getopts u:p:a:b:n:l:m:s:t:f: option
do
 case "${option}"
 in
 u)  export USER=${OPTARG};;
 p)  export PASS=${OPTARG};;
 a)  export SAIHOST=${OPTARG};;
 b)  export SAIPORT=${OPTARG};;
 n)  export NAME=${OPTARG};;
 l)  export ANONUSER=${OPTARG};;
 m)  export ANONPASS=${OPTARG};;
 s)  export SAIDOCKERHOST=${OPTARG};;
 t)  export SAIDOCKERPORT=${OPTARG};;
 f)  export ProfileFileName=${OPTARG};;

 esac
done
ENCODED="$(echo $USER:$PASS|base64)"

JSON=$(envsubst<../smc/$ProfileFileName)

echo
echo $JSON
echo

echo $JSON |  curl -v  -k \
 -H "Authorization: Basic $ENCODED" \
 -H "Content-Type: application/json" \
 -X POST \
https://$SAIHOST:$SAIPORT/siebel/v1.0/cloudgateway/profiles/swsm/ \
-d @-

