#!/bin/bash
while getopts u:p:a:b:d:n: option
do
 case "${option}"
 in
 u)  export USER=${OPTARG};;
 p)  export PASS=${OPTARG};;
 a)  export SAIHOST=${OPTARG};;
 b)  export SAIPORT=${OPTARG};;
 d)  export PROFILE=${OPTARG};;
 n)  export NAME=${OPTARG};;
 esac
done
ENCODED="$(echo $USER:$PASS|base64)"

JSON=$(envsubst<../smc/deployMigration.json)

echo
echo $JSON
echo 

curl -i -v  -k   \
-H "Authorization: Basic $ENCODED" \
-H "Content-Type: application/json" \
-X DELETE \
https://$SAIHOST:$SAIPORT/siebel/v1.0/cloudgateway/deployments/migrations/$NAME

echo $JSON |  curl -v  -k -H "Content-Length: ${#JSON}"  \
 -H "Authorization: Basic $ENCODED" \
 -H "Content-Type: application/json" \
 -X POST \
https://$SAIHOST:$SAIPORT/siebel/v1.0/cloudgateway/deployments/migrations/ \
-d @-

